# This workflow executes CI jobs

name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches: '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6]
        os: [windows-latest, ubuntu-latest, macos-latest]
    permissions:
      id-token: write
      contents: read
    name: Build on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Validate commit messages 
        uses: wagoid/commitlint-github-action@v4
        if: matrix.os == 'ubuntu-latest'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install CLI and verify
        run: |
          python -m pip install --upgrade pip
          pip install .
          gdk --help
      - name: Lint with flake8
        run: |
          pip3 install flake8
          # The GitHub editor is 127 chars wide
          flake8 . --count --max-complexity=10 --max-line-length=127 --show-source --statistics
      - name: Testing CLI (Runs both unit and integration tests)
        run: |
          pip install -r test-requirements.txt
          coverage run --source=gdk -m pytest -v -s tests integration_tests && coverage xml --fail-under=90
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.GDK_WORKFLOW_AWS_ROLE}}
          aws-region: us-east-1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run UATs 
        run: | 
          coverage run --source=gdk -m pytest -v -s uat
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2